
server.port=9091
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb  //move to the cloud config server

spring.application.name=User-service
eureka.instance.hostname=localhost



